A.3.24.0900 changes
4bbakers/redcap_rsvc pull request #171
Opened 2024-12-20 19:45 UTC by ellisthomas

A.3.24.0900 changes

2024-12-23 15:53 UTC, mmcev106 requested changes
@ellisthomas, your changes look great in general.  I have two requests:

- Whenever `on the dropdown field labeled` syntax is used, I believe we should specify the label for the whole dropdown field afterward, as opposed to specifying the option a second time.  Does that make sense?  If so, are you able to make that change?
- I am seeing the failure in the following screenshot when I run this test.  I suspect the difference is that I'm running a more up to date copy of the RCTF library on my local.  I have an item on my TODO list to make it easy for you to update RCTF on your local.  In the meantime, could you look into whether this step makes sense to you from a manual testing perspective?  I'm guessing it doesn't based on the step & circuled language in the screenshot.

![image](https://github.com/user-attachments/assets/a8043873-481f-48cc-bc5d-2959340811be)

2024-12-23 16:02 UTC, ellisthomas commented
@mmcev106 Yes, I can make the changes for when selecting a dropdown option. 
For the item have circled if I am not mistaken that step should be referring to the tabs at the top and not the video link.

2024-12-23 16:27 UTC, mmcev106 commented
@ellisthomas, I suspect you're right on `should NOT see "e-Consent Framework"` step.  Do you see a way to modify the step that avoids this pitfall?

2024-12-23 16:46 UTC, mmcev106 commented
@ellisthomas, I'm guessing [your response on issue #22](https://github.com/4bbakers/redcap_rsvc/issues/22#issuecomment-2559994571) might have been intended to be in response to this PR.  That would involve a change to RCTF (so non-trivial).  Do you also think it would be a valid change logically to verify this step via the circled button in the screenshot rather than the tab on the PDF Snapshots page?

2024-12-23 16:55 UTC, ellisthomas commented
@mmcev106 Yes it could be an option. Let me verify if it this button is effected by this change in the control center

2024-12-23 16:59 UTC, ellisthomas commented
@mmcev106 I can confirm it does hide it on the "Online Designer" so I think we can move forward with your suggested changes.

2025-01-08 21:14 UTC, mmcev106 commented
@ellisthomas, I am closing this as the changes for A.3.24.0900 were already merged via #188.  There is a bug on github.com still showing them in this PR, even though A.3.24.0900 is now identical between v14.7.0 and this branch.  I am closing this because there are other commits in this branch for files other than A.3.24.0900 that look like they are not ready to be reviewed yet.

2025-01-08 21:14 UTC, closed without merging